/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cantina.telas;

import br.com.cantina.modeldb.Cliente;
import br.com.cantina.modeldb.Transacao;
import br.com.cantina.modeldb.controller.TransacaoJpaController;
import br.com.cantina.utils.Utils;
import br.com.cantina.utils.ControllerProvider;
import br.com.cantina.utils.Table;
import java.util.List;
import javax.persistence.TypedQuery;
import javax.swing.border.TitledBorder;

/**
 *
 * @author ntbra
 */
public class DetailClientTransactions extends javax.swing.JDialog {
    private final Table table;
    private final TransacaoJpaController controller = ControllerProvider.getTransacaoJpaController();
    private Cliente cliente;
    private List<Transacao> transactions;
    /**
     * Creates new form DetailClientTransactions
     */
    public DetailClientTransactions(java.awt.Frame parent, Cliente cliente) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;
        table = (Table)jTable1;
        setTitle("Detalhes");
        ((TitledBorder)jPanel1.getBorder()).setTitle(cliente.getNome());
        preencheTable();
    }
    
    
    private void preencheTable(){
        table.clearAll();
        
        TypedQuery<Transacao> query =  controller.getEntityManager()
                .createNamedQuery("Transacao.findByIdcliente", Transacao.class)
                .setParameter("idcliente", cliente.getIdcliente());
        
        transactions = query.getResultList();
        transactions.stream().forEach((t) -> {
            table.getDefaultTableModel().addRow(new String[]{t.getType().equals("venda")?"Compra":"Pagamento",
                        Utils.DATE_TIME_FORMAT.format(t.getTimestamp()),
                        Utils.FORMATTER.format(t.getValue())});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new Table(new String[]{"Tipo", "Data/Hora", "Valor"});

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Title", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jTable1.setModel(null);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
